#!/bin/bash

# ========================================
# Memory Decoder Training Configuration for GPT-2 small (NPU)
# ========================================

# Model Configuration
# Options: gpt2, qwen2, qwen2.5
MODEL_FAMILY="gpt2"
MODEL_SIZE="small"
KNN_MODEL_SIZE="xl"

# Auto-detect dimension based on model family
if [ "$MODEL_FAMILY" == "gpt2" ]; then
    case "$MODEL_SIZE" in
        "small") DIMENSION=768 ;;
        "medium") DIMENSION=1024 ;;
        "large") DIMENSION=1280 ;;
        "xl") DIMENSION=1600 ;;
        *) DIMENSION=768 ;;
    esac
elif [ "$MODEL_FAMILY" == "qwen2" ]; then
    case "$MODEL_SIZE" in
        "0.5B") DIMENSION=896 ;;
        "1.8B") DIMENSION=2048 ;;
        "7B") DIMENSION=4096 ;;
        "14B") DIMENSION=5120 ;;
        "72B") DIMENSION=8192 ;;
        *) DIMENSION=4096 ;;
    esac
elif [ "$MODEL_FAMILY" == "qwen2.5" ]; then
    case "$MODEL_SIZE" in
        "0.5B") DIMENSION=896 ;;
        "1.5B") DIMENSION=1536 ;;
        "3B") DIMENSION=2048 ;;
        "7B") DIMENSION=3584 ;;
        "14B") DIMENSION=5120 ;;
        "32B") DIMENSION=6144 ;;
        "72B") DIMENSION=8192 ;;
        *) DIMENSION=1536 ;;
    esac
else
    echo "Unknown model family: $MODEL_FAMILY"
    exit 1
fi

# Dataset Configuration
DATASET_NAME="wikitext"
SUBSET="train"

# Path Configuration
DATASET="/data/processed_data/wikitext-gpt2"
ACCELERATE_CONFIG="./accelerate_config/${MODEL_FAMILY}.yaml"

# KNN signals generated by save_pipeline.sh (using gpt2-xl)
KNN_DSTORE_DIR="./dstore/${MODEL_FAMILY}-${KNN_MODEL_SIZE}/${DATASET_NAME}"
KNN_DSTORE_PATH="${KNN_DSTORE_DIR}/knn_${MODEL_FAMILY}_${SUBSET}_1600.arrow"

# Base model for training Memory Decoder (using gpt2-small)
MODEL="/data/model/gpt2-small"

# Output directory for Memory Decoder checkpoints
OUTPUT_DIR="./results/memdec-${MODEL_FAMILY}-${MODEL_SIZE}-knn${KNN_MODEL_SIZE}-${DATASET_NAME}"

mkdir -p ${OUTPUT_DIR}

# NPU Environment Setup
export ACCELERATE_USE_ASCEND=true
source /usr/local/Ascend/ascend-toolkit/set_env.sh
export LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:$LD_LIBRARY_PATH

# HCCL Optimization
export HCCL_INTRA_ROCE_ENABLE=1
export HCCL_INTRA_ROCE_HF=1
export HCCL_INTER_LINK_PORT=2
export HCCL_SOCKET_IFNAME=eth0
export HCCL_OP_BASE_ACK_TIMEOUT=300
export HCCL_NIC_POLICY=RDMA
export HCCL_DYNAMIC_OPTIMIZE=1

export PYTHONPATH=$PYTHONPATH:.
export PYTHONUNBUFFERED=1

# ========================================
# Pipeline Execution
# ========================================

echo "=========================================="
echo "Memory Decoder Training"
echo "=========================================="
echo "Model: ${MODEL_FAMILY}-${MODEL_SIZE}"
echo "Dataset: ${DATASET_NAME}"
echo "Subset: ${SUBSET}"
echo "Dimension: ${DIMENSION}"
echo "=========================================="
echo ""
echo "Model path: ${MODEL}"
echo "KNN dstore path: ${KNN_DSTORE_PATH}"
echo "Output directory: ${OUTPUT_DIR}"
echo "=========================================="
echo ""

/root/anaconda3/envs/memtest/bin/accelerate launch \
    --config_file ${ACCELERATE_CONFIG} \
    -m \
    train_memdec \
    --model_name_or_path ${MODEL} \
    --dataset_name ${DATASET} \
    --dataset_split_name ${SUBSET} \
    --knn_save_path ${KNN_DSTORE_PATH} \
    --output_dir ${OUTPUT_DIR} \
    --learning_rate 1e-3 \
    --lr_scheduler_type linear \
    --gradient_accumulation_steps 8 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --num_train_epochs 70 \
    --seed 42 \
    --block_size 1024 \
    --checkpointing_steps "epoch" \
    --with_tracking \
    --report_to wandb \
    --project_name "MemoryDecoder" \
    --run_name "gpt2-small-knnxl-wikitext" \
    --group_name "gpt2-small-knnxl"